# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
      - image: circleci/redis:5.0.4
        environment:
          BUNDLER_VERSION: 2.0.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: gem install bundler
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # run tests!
      - run:
          name: Collect and filter specs
          command: |
            mkdir -p tmp/circleci
            circleci tests glob "spec/**/*_spec.rb" > tmp/circleci/all_tests.txt
            circleci tests split --split-by=timings < tmp/circleci/all_tests.txt > tmp/circleci/tests_to_run.txt
            echo "These specs will be run:"
            cat tmp/circleci/tests_to_run.txt
      - run:
          name: Parallel RSpec
          command: |
            bin/rspec \
              --color \
              --format progress \
              --require spec_helper \
              --format RSpec::Instafail \
              --format RspecJunitFormatter --out /tmp/rspec/junit.xml \
              $(cat tmp/circleci/tests_to_run.txt)
      # actually not necessary for test results to be collected, but these files
      # won't show up in the web UI otherwise
      - store_artifacts:
          path: /tmp/rspec/
          destination: rspec

      - store_test_results:
          path: /tmp/rspec/