version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.3-node
      - image: cimg/redis:6.0.16

    working_directory: ~/repo

    steps:
      - checkout

      - ruby/install-deps:
          key: gems-v2
          include-branch-in-cache-key: false
      - ruby/rspec-test